### ISSUE TITLE
Debug Goldsky Java client creation issue

### ISSUE THREAD

**Issue by nand4011** [momentohq/client-sdk-java#308]
Goldsky is seeing a stack trace when creating clients on multiple threads:
`Jul. 31, 2023 4:24:39 P.M. io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=3, target=cache.cell-4-us-west-2-1.prod.a.momentohq.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:100)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:60)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:51)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:631)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at momento.sdk.ScsDataGrpcStubsManager.setupChannel(ScsDataGrpcStubsManager.java:92)
	at momento.sdk.ScsDataGrpcStubsManager.<init>(ScsDataGrpcStubsManager.java:76)
	at momento.sdk.ScsDataClient.<init>(ScsDataClient.java:155)
	at momento.sdk.CacheClient.<init>(CacheClient.java:81)
	at momento.sdk.CacheClientBuilder.build(CacheClientBuilder.java:38)
	at com.goldsky.strick.sink.momento.MomentoClient.init(MomentoClient.scala:30)
	at com.goldsky.strick.sink.MomentoSink.<init>(MomentoSink.scala:28)
	at com.goldsky.strick.pipeline.TableExecutionBehaviour.$anonfun$executeTransformsAndSinks$3(TableExecutionBehaviour.scala:203)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.goldsky.strick.pipeline.TableExecutionBehaviour.$anonfun$executeTransformsAndSinks$1(TableExecutionBehaviour.scala:65)
	at com.goldsky.strick.pipeline.TableExecutionBehaviour.$anonfun$executeTransformsAndSinks$1$adapted(TableExecutionBehaviour.scala:58)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.goldsky.strick.pipeline.TableExecutionBehaviour.executeTransformsAndSinks(TableExecutionBehaviour.scala:58)
	at com.goldsky.strick.pipeline.TableExecutionBehaviour.executeTransformsAndSinks$(TableExecutionBehaviour.scala:48)
	at com.goldsky.strick.pipeline.FromKafkaPipeline.executeTransformsAndSinks(FromKafkaPipeline.scala:15)
	at com.goldsky.strick.pipeline.FromKafkaPipeline.run(FromKafkaPipeline.scala:104)
	at com.goldsky.strick.pipeline.FromKafkaPipeline.run(FromKafkaPipeline.scala:15)
	at com.goldsky.strick.Executor$.delayedEndpoint$com$goldsky$strick$Executor$1(Executor.scala:69)
	at com.goldsky.strick.Executor$delayedInit$body.apply(Executor.scala:18)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at com.goldsky.strick.Executor$.main(Executor.scala:18)
	at com.goldsky.strick.Executor.main(Executor.scala)`

**Comment by nand4011** [comment]
The issue turned out to be them missing a call to close() on the client.
